baseURL = 'https://bejewelled-meerkat-aa1da9.netlify.app/'
languageCode = 'en-us'
title = 'Nihal Sahu'
theme = 'nihalsahu.net'

[menu]
  [[menu.main]]
    name = "home"
    pre = "home"
    url = "/"
    weight = 1

  [[menu.main]]
    name = "essays"
    pre = "essays"
    url = "/essays"
    weight = 1
[markup.goldmark.renderer]
unsafe= true
